### ISSUE TITLE
Plug-in installed and config set-up but GTM doesn't find my container-id

### ISSUE THREAD

**Issue by OakNiels** [mib200/vue-gtm#109]
Hi, 

This is my config file:

```ts
import Vue from 'vue';
import VueGtm from 'vue-gtm';
import router from '@/router';
import env from '../../env.config';

const GOOGLE_TAG_MANAGER_ID = env.GOOGLE_TAG_MANAGER_ID;

Vue.use(VueGtm, { id: GOOGLE_TAG_MANAGER_ID, enabled: true, vueRouter: router, debug: true });
```

My tag assistant says that the global sitetag(gtag.js) is undefined. 

I tried to also include the tracking code to my index.html and excluded the id from my config file but then it won't work with a SPA. The datalayer always contains the path of my homepage. When I open my preview in GTM it says that there are 2 containers where one is undefined. 

Basically what I want to achieve is the send pageviews to my GA account. I already set-up a GA tag and created a custom event trigger which a named content-view, If I'm correct my route is synced and should map the datalayer every time a route change happens not? 

Is there anyone who could help me? 

![image](https://user-images.githubusercontent.com/77064756/103786000-2d1bf980-503c-11eb-950f-a93945be761e.png)

**Comment by Shinigami92** [comment]
Are you using Vue 2 or 3? If you are using Vue 2 do you have the correct dependency version? (Instructions can be found in README)

Do you see any browser console output related to vue-gtm's `debug: true`?

Do you have any JS blocker like `ScriptSafe` or `uBlock`?

**Comment by OakNiels** [comment]
I'm using Vue2: dependencies : "vue-gtm": "3.0.0-vue2", 
Removed node modules and installed again.

I have no JS blocker installed. And I can't see any browser output in my debug mode. 

![image](https://user-images.githubusercontent.com/77064756/104856812-d86a5f80-5914-11eb-892b-865a2468091e.png)

![image](https://user-images.githubusercontent.com/77064756/104856826-e7511200-5914-11eb-92bd-e59e86354daa.png)

![image](https://user-images.githubusercontent.com/77064756/104856840-f46e0100-5914-11eb-8a09-344a30e7be29.png)

So I really don't know what I'm doing wrong here.

**Comment by Shinigami92** [comment]
Sorry that I need to tell you that I only took over this repository to at least support TypeScript and Vue 3 support.
So I'm not a user of Google Analytics myself and can only do my best without knowing it directly.

One thing I'm curious about is GTM and GA are near together but different. So maybe you should try another plugin that supports GA instead of GTM.

E.g. [this](https://github.com/MatteoGabriele/vue-analytics) plugin seems to load [`https://www.google-analytics.com`](https://github.com/MatteoGabriele/vue-analytics/blob/master/src/bootstrap.js#L25), but our repo _only_ loads [`https://www.googletagmanager.com/gtm.js`](https://github.com/mib200/vue-gtm/blob/master/src/utils.ts#L48)

I'm just guessing here because I see GA instead of GTM on your screenshots.

You could also try the methods `trackView` or `trackEvent` from our plugin and look in the browser console again, cause these both methods are the once that logs to the console.
_Maybe I should provide more debug logging like plugin successfully initialized_ :thinking:  

If some of these hints are correct, please let me know what solved your problem so I can mention it in the README for other users.

**Comment by obe-ws** [comment]
> I'm using Vue2: dependencies : "vue-gtm": "3.0.0-vue2",
> Removed node modules and installed again.
> 
> I have no JS blocker installed. And I can't see any browser output in my debug mode.
> 
> ![image](https://user-images.githubusercontent.com/77064756/104856812-d86a5f80-5914-11eb-892b-865a2468091e.png)
> 
> ![image](https://user-images.githubusercontent.com/77064756/104856826-e7511200-5914-11eb-92bd-e59e86354daa.png)
> 
> ![image](https://user-images.githubusercontent.com/77064756/104856840-f46e0100-5914-11eb-8a09-344a30e7be29.png)
> 
> So I really don't know what I'm doing wrong here.

Same problem with  "vue-gtm": "3.1.1-vue2" here.

**Comment by Shinigami92** [comment]
There aren't any significant changes between 3.0.0 and 3.1.1 that are related to your problem.

Please try some things from my comment above: https://github.com/mib200/vue-gtm/issues/109#issuecomment-762058866

**Comment by Shinigami92** [comment]
If everything is okay now (and my comment above may helped you) feel free to close the issue or contact me here so I can close it
Otherwise I will close it in around a week

If something is not resolved, please provide a comment
