### ISSUE TITLE
Bug: trackingCallError due to unauthorized response from siteeuwest.slgnt.eu

### ISSUE THREAD

**Issue by mrwatts** [mib200/vue-gtm#110]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.1.1-vue2        |
| Vue    | v2.6.12        |
| VueRouter | v3.4.9   |

## Input

```js
Vue.use(VueGtm, {
  id: 'GTM-XXXXXX',
  queryParams: {
    gtm_auth:'xxxxxxxxxxxxxxxxxxxxxx',
    gtm_preview:'env-723',
    gtm_cookies_win:'x'
  },
  defer: true,
  compatibility: false,
  debug: true,
  vueRouter: router,
  trackOnNextTick: false
});
```

When starting the app, the following error is logged in the console:

```js
{trackingCallItems: null, originalTrackingCall: {…}, cleanedTrackingCall: {…}, requestPending: false, trackingCallError: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at http:/…}
```

This is caused by a 401 unauthorized response from: https://siteeuwest.slgnt.eu/track.
Also, I do not understand where the payload that is being sent here, comes from. It seems like dummy test data to me:

```js
{universeId: "126307df-f836-4509-903e-1e902b53d129", profile: null, profileId: null,…}
allowCookies: true
allowLocalStorage: true
async: true
exposedFields: [{field: "The_MASTER_MY_FINAL_SITE_IDENTIFIER_value"}]
isEvent: false
isTargeting: true
metaTags: {}
pageTitle: "app"
placements: [4965, 4985, 4991]
profile: null
profileId: null
referer: "http://localhost:8080/"
tagValues: [{tag: "testtag", value: ""}]
universeId: "126307df-f836-4509-903e-1e902b53d129"
url: "http://localhost:8080/"
```

**Comment by Shinigami92** [comment]
Maybe you should ask for help on Stack Overflow?

**Comment by mrwatts** [comment]
Well I don't know what I would have to ask.

All I did was initialize the plugin as shown. There is no tracking code in my app. Only the router was attached.

For the record, router tracking _is_ working. I just don't understand what is causing this initial failing request.

**Comment by Shinigami92** [comment]
So I'm not 100% sure but for your second question maybe it's just the `debug: true` flag?
If you turn debug off, is it still there?

Every logging output of this plugin is prefixed with `"VueGtm :"`, see [here](https://github.com/mib200/vue-gtm/blob/master/src/utils.ts#L11)

So maybe these log outputs are not directly from this plugin.

I think your chances are much greater to just try to explain your problem to the Stack Overflow community, because I don't think I can help you much here.

Just link your Stack Overflow question to this issue + add your link here in a response.

**Comment by mrwatts** [comment]
Hi,

I investigated a little further and I am convinced now as well that it isn't related to this plugin. It has to do with some other configuration on the GTM side I think.

You may close this issue.

Thank you for responding quickly.

Martin
