### ISSUE TITLE
ignoredViews not working

### ISSUE THREAD

**Issue by alexauvray** [mib200/vue-gtm#73]
Is IgnoredViews really working ?

Vue.use(VueGtm, {
  id: "GTM-XXXXX",
  enabled: true,
  vueRouter: router,
  ignoredViews: ["test"]
});

I still have some GTM tags that are played on the "test" route though...

**Comment by RexHung0302** [comment]
Did you resolve this? I got the same problem.

**Comment by chinciusan** [comment]
Hi, any news on this? It happens to me too.

**Comment by Shinigami92** [comment]
Hi o/ , I'm a new co-maintainer of this repo :)
Currently I'm to much involved in maintaining my own repo `@prettier/plugin-pug`

So if someone else can provide a pull request, I'm happy to review and try to help
Otherwise you need to wait a little bit until I have time to focus on this issue

**Comment by Shinigami92** [comment]
Could someone of you provide me what routes do you have? Especially route `name`s

https://github.com/mib200/vue-gtm/blob/7f93e888d33f511c0eda00e991c63a99ac31b5f0/src/index.js#L57-L59

**Comment by chinciusan** [comment]
@Shinigami92 it seems to be working fine. I was expecting GTM not to be loaded, but actually it is loaded, but no event is triggered for it on ignoredViews. 
Maybe this should be mentioned in the readme description. I believe you can close this issue.

**Comment by Shinigami92** [comment]
Thank you very much
I will try to add something to the readme and after that I will close this issue 👍

**Comment by Shinigami92** [comment]
Done in https://github.com/mib200/vue-gtm/commit/2ac0ae461e7a2f1d073277cd4088e85982737bd9

**Comment by ZhenyaMelnichuk** [comment]
Hello, I also encountered the problem of ignoredViews not working.
What my code looked like...

app.use(
		 createGtm({
				id: 'GTM-****',
				vueRouter: router,
				ignoredViews: ['EditPost', 'NewReview', 'NewPost']
			})
		);

The problem is that ignoredView is not compared to the original page name, but to the lowercase page name.
https://github.com/mib200/vue-gtm/blob/7f93e888d33f511c0eda00e991c63a99ac31b5f0/src/index.js#L58-L61

Therefore, ignoredViews should have looked like this: ['editpost', 'newreview', 'newpost']
I don’t understand why the toLowerCase function is there?
I would like to see information about this nuance in the readme.
